### ISSUE TITLE
Errorthandling with check.js

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repositories#2306]
Check.js script fails if the sources-dist-*.json is invalid, even if it has been corrected at a later commit within the PR:

```
adapters filtered:
imap
---
SyntaxError: Unexpected string in JSON at position 49635
    at JSON.parse (<anonymous>)
    at detectChanges (/home/runner/work/ioBroker.repositories/ioBroker.repositories/lib/check.js:144:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async detectAffectedAdapter (/home/runner/work/ioBroker.repositories/ioBroker.repositories/lib/check.js:159:29)
    at async doIt (/home/runner/work/ioBroker.repositories/ioBroker.repositories/lib/check.js:270:19)
```

I would suggest:
-) to add more infos to the exception, i.e. filename
-) log the data (if possible and usable - to be checked)
-) abort this co mit but continue with the next commit. 

In general its NOT the job of check.js to verify the correct syntax of the sources-*.json files. There are other jobs doing this anyway. So it should nozt be a problem to skip this error / skip this commit.

(I can take care of this when time is available).

**Comment by mcm1957** [comment]
see #807
