### ISSUE TITLE
ioBroker states wrong version in latest repository

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.repositories#535]
The file `http://repo.iobroker.live/sources-dist-latest.json` indicates `v2.0.1` for the hue-extended adapter, even though the version `v1.1.5` is latest on npm (see https://www.npmjs.com/package/iobroker.hue-extended).

Though, I accidentally pushed v2.0.1 to npm earlier but overrode it afterwards:

![image](https://user-images.githubusercontent.com/14368811/68420852-815bed00-019d-11ea-84e2-1b1805693bdf.png)

Apparently ioBroker is not retrieving the latest version but probably the highest number?
Is it possible to fix that? I would not want to push a version v2.0 of my adapter to npm just because I accidentally pushed a wrong version earlier.

Thanks in advanced for your help.

**Comment by Zefau** [comment]
@Apollon77 sorry for pinging, but could you help on this? I was looking through all the code but can't find any evidence that leads to the wrong version number.

https://registry.npmjs.org/iobroker.hue-extended holds the correct value.

By the way, running `node build --versions` throws following error at the end:
```
C:\Users\Zefau\Projects\ioBroker.repositories\lib\build.js:272
                updatePublishes((latest, stable) => {
                ^

TypeError: updatePublishes is not a function
    at getStats (C:\Users\Zefau\Projects\ioBroker.repositories\lib\build.js:272:17)
    at Request.request [as _callback] (C:\Users\Zefau\Projects\ioBroker.repositories\lib\build.js:29:9)
    at Request.self.callback (C:\Users\Zefau\Projects\ioBroker.repositories\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\Zefau\Projects\ioBroker.repositories\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\Zefau\Projects\ioBroker.repositories\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
```

**Comment by Apollon77** [comment]
@GermanBluefox

**Comment by Zefau** [comment]
@GermanBluefox I would highly appreciate your feedback on this. Why does `http://repo.iobroker.live/sources-dist-latest.json` hold the wrong version number?
I was looking through the source code and looks fine to me.

`npm view iobroker.hue-extended version` returns `1.1.5`, which is correct. Though, iobroker states a wrong version (v2.0.1).

**Comment by Zefau** [comment]
I contacted the npm support to get the version `2.0.1` deleted from npm. Bug still exists in iobroker.

**Comment by Apollon77** [comment]
then we leasve this issue open

**Comment by foxriver76** [comment]
Very similar to https://github.com/ioBroker/ioBroker.repositories/issues/527

**Comment by GermanBluefox** [comment]
Actually this issue is fixed.
